### ISSUE TITLE
Issue with the version 0.6.0: couldn't find file 'growlyflash' (js)

### ISSUE THREAD

**Issue by Dinuz** [estum/growlyflash#15]
Hi @estum,

I tried out the new version of growlyflash, and I get a weird message:

couldn't find file 'growlyflash' in app/assets/javascripts/application.js

I thought at the beginning that it was related with me updating my ruby version, but after I immediately realized it was related with the new growlyflash version.

I kept everything the same (with my upgrade ruby version, and rails 4.2), and I just downgraded growlyflash to the 0.5.0 version, and everything was working well.

I didn't look into the new addition in the code, but I cannot load the growlyflash.js for the life of me using the 0.6.0 version.

Do you have any idea?

**Comment by estum** [comment]
@Dinuz sorry for the late reply, please, update gem.

**Comment by Dinuz** [comment]
@estum I see the railtie was creating the issue.
Do you have idea why?

Anyway I did a small modification to the gem (in order to use a switch on the title,as it was in the default options and in the readme - note that the code before was based on the option to be different from null). I changed it in a switch because actually make more sense, and moreover was the simplest of the change. The readme was creating confusion otherwise (and if not extended with null, the title was always present). You should update the gem, in order to allow to get the new code when bundle install.

Now everything works smooth!!!

**Comment by estum** [comment]
@Dinuz dynamic assets is only available with `Rails::Engine`, I just made useless commit and didn't check that.

**Comment by Dinuz** [comment]
@estum nothing is useless....we just learned that dynamic assets is only available with engine:))
