### ISSUE TITLE
Customize. Deploy fails

### ISSUE THREAD

**Issue by pmaojo** [estum/growlyflash#28]
Hello, 

I must be doing something wrong. I paste the custom styles on application.js and when I deploy I get error.

`$.bootstrapGrowl.defaults = $.extend on, $.bootstrapGrowl.defaults,
  width:       250
  delay:       4000
  spacing:     10
  target:      'body'
  dismiss:     true
  type:        success
  align:       'center'
  alignAmount: 20
  offset:      
    from:      'top'
    amount:    20`

Where should I insert the customizing code and how? 

Thankyou!

**Comment by estum** [comment]
@pmaojo Hello,

There is [a chapter](https://github.com/estum/growlyflash#customize) in the readme.
