### ISSUE TITLE
XHR notices don't work where as non XHR does

### ISSUE THREAD

**Issue by atinder90** [estum/growlyflash#30]
I have installed and setup the gem as shown in readme.
Normal notices or shown but when something done with ajax, no notice is shown.
I added use_growlyflash in application controller.
Am i missing any configuration ?

**Comment by estum** [comment]
@atinder90, please, check a XHR response for the `X-Message` header and, also, check handlers on `ajax:complete ajaxComplete` events (just add another one handler to see if it fires). You can also set `Growlyflash.debug = true;` in the browser console and see some debug messages.

**Comment by atinder90** [comment]
thanks for replying so fast.
ye X-Message was not set per api because i was trying to to it like this

`format.json { render :show, status: :ok, location: @playlist, notice: 'Playlist was successfully updated.' }`

fixed it by using following code.
```

flash[:notice] = "Playlist was successfully updated."
format.json { render :show, status: :ok, location: @playlist }
```
